# start service : docker compose up
# stop service  : docker compose down
# link akses    : localhost:{PORT}
version: "3.9"

services:
  nginx:
    image: nginx:1.23.1-alpine
    ports:
      - "{PORT}:80"
    volumes:
      - ./:/var/www/html/
      - ./docker-config/nginx/local.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - dev-net
  php-fpm:
    build:
      context: ./
      dockerfile: ./docker-config/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html/
    networks:
      - dev-net
networks:
  dev-net:
    name: dev-net
    driver: bridge
